# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jhoward/git/fastforest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jhoward/git/fastforest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhoward/git/fastforest/CMakeFiles /home/jhoward/git/fastforest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhoward/git/fastforest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fastforest

# Build rule for target.
fastforest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastforest
.PHONY : fastforest

# fast build rule for target.
fastforest/fast:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/build
.PHONY : fastforest/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

fastforest.o: fastforest.cpp.o

.PHONY : fastforest.o

# target to build an object file
fastforest.cpp.o:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest.cpp.o
.PHONY : fastforest.cpp.o

fastforest.i: fastforest.cpp.i

.PHONY : fastforest.i

# target to preprocess a source file
fastforest.cpp.i:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest.cpp.i
.PHONY : fastforest.cpp.i

fastforest.s: fastforest.cpp.s

.PHONY : fastforest.s

# target to generate assembly for a file
fastforest.cpp.s:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest.cpp.s
.PHONY : fastforest.cpp.s

fastforest_py.o: fastforest_py.cpp.o

.PHONY : fastforest_py.o

# target to build an object file
fastforest_py.cpp.o:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest_py.cpp.o
.PHONY : fastforest_py.cpp.o

fastforest_py.i: fastforest_py.cpp.i

.PHONY : fastforest_py.i

# target to preprocess a source file
fastforest_py.cpp.i:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest_py.cpp.i
.PHONY : fastforest_py.cpp.i

fastforest_py.s: fastforest_py.cpp.s

.PHONY : fastforest_py.s

# target to generate assembly for a file
fastforest_py.cpp.s:
	$(MAKE) -f CMakeFiles/fastforest.dir/build.make CMakeFiles/fastforest.dir/fastforest_py.cpp.s
.PHONY : fastforest_py.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fastforest"
	@echo "... run"
	@echo "... fastforest.o"
	@echo "... fastforest.i"
	@echo "... fastforest.s"
	@echo "... fastforest_py.o"
	@echo "... fastforest_py.i"
	@echo "... fastforest_py.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

